DATASET_DIR=/home/pmarce/datasets/VOCdevkit/VOC2007/train_tfrecords
TRAIN_DIR=./
CHECKPOINT_PATH=/home/pmarce/checkpoints/model.ckpt-80117
python3 ../train_ssd_network.py \
    --train_dir=${TRAIN_DIR} \
    --dataset_dir=${DATASET_DIR} \
    --dataset_name=pascalvoc_2007 \
    --dataset_split_name=train \
    --model_name=ssd_300_vgg \
    --checkpoint_path=${CHECKPOINT_PATH} \
    --save_summaries_secs=60 \
    --save_summaries_secs=60 \
    --save_interval_secs=600 \
    --weight_decay=0.00001 \
    --optimizer=adam \
    --learning_rate=0.0005 \
    --num_epochs_per_decay=5 \
    --learning_rate_decay_factor=0.98 \
    --batch_size=1\
    --max_number_of_steps=450000 \
    --weighted_loss=True
